# Generated by Django 5.1.6 on 2025-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('teamlead', 'Team Lead'), ('project_manager', 'Project Manager'), ('manager', 'Manager'), ('admin', 'Admin')], default='employee', max_length=50),
        ),
    ]
