# Generated by Django 5.1.6 on 2025-07-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='office_working_hours',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('teamlead', 'Team Lead'), ('project_manager', 'Project Manager'), ('manager', 'Manager'), ('admin', 'Admin')], default='employee', max_length=50),
        ),
        migrations.AlterModelTable(
            name='settings',
            table='app_settings',
        ),
    ]
