# Generated by Django 5.1.6 on 2025-07-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_users_details_to_employee_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='is_working_day',
        ),
    ]
