# Generated by Django 5.1.6 on 2025-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_is_working_day_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='day',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.UniqueConstraint(fields=('day',), name='unique_day_entry'),
        ),
    ]
