# Generated by Django 5.1.6 on 2025-07-29 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_settings_day_settings_unique_day_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('intern', 'Intern'), ('trainee', 'Trainee'), ('junior', 'Junior'), ('senior', 'Senior'), ('teamlead', 'TeamLead'), ('developer', 'Developer'), ('designer', 'Designer'), ('projectmanager', 'Project Manager'), ('qa', 'Quality Assurance'), ('hr', 'Human Resources'), ('admin', 'Admin'), ('ceo', 'CEO')], max_length=50)),
                ('date_promoted', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='app.users')),
            ],
        ),
    ]
