# Generated by Django 5.1.6 on 2025-07-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employee_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_designation',
            old_name='date_promoted',
            new_name='date_assigned',
        ),
    ]
