# Generated by Django 5.1.6 on 2025-06-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_officehours_tasks_taskactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
