# Generated by Django 5.1.6 on 2025-06-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tasks_submitted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='expected_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
