# Generated by Django 5.1.6 on 2025-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tasks_expected_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_ceo', models.CharField(blank=True, max_length=100, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_founded_date', models.DateField(blank=True, null=True)),
                ('company_social_media_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
