# Generated by Django 5.1.6 on 2025-06-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_companydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='company_ceo',
        ),
    ]
