# Generated by Django 5.1.6 on 2025-06-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_companydetails_company_ceo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
    ]
