# Generated by Django 5.1.6 on 2025-06-12 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_employeeprofile'),
        ('users', '0002_alter_signupuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.signupuser')),
            ],
        ),
    ]
