# Generated by Django 5.1.6 on 2025-06-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_chatmessage'),
        ('users', '0002_alter_signupuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.signupuser')),
            ],
            options={
                'verbose_name_plural': 'Task Read Statuses',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
