# Generated by Django 5.1.6 on 2025-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_taskreadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreadstatus',
            name='last_read_at',
            field=models.DateTimeField(),
        ),
    ]
